services:
  racecar:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        BASE_IMAGE: sebagarc/racecar2
        DOCKER_UID: 1000
        DOCKER_GID: 1000
    image: local/racecar-sim
    privileged: true
    # user: "1000:1000"
    entrypoint: /home/dockeruser/racecar_ws/src/libracecar/docker/entrypoint_sim_alan.sh
    environment:
      - DISPLAY=${DISPLAY}
      # have /etc/profile.d/xdg_dirs_desktop_session.sh initialize XDG_DATA_DIRS
      - DESKTOP_SESSION=NONEMPTY
      # otherwise qt cant find icons by default so rqt_graph doesnt work
      - XDG_CURRENT_DESKTOP=GNOME
      - LOCALE_ARCHIVE=${LOCALE_ARCHIVE}
    volumes:
      - ../../racecar_ws_src:/home/dockeruser/racecar_ws/src
      - /nix:/nix
      - ${HOME}/.emacs.d:/home/dockeruser/.emacs.d
      - ${HOME}/.ssh:/home/dockeruser/.ssh
      - ${HOME}:${HOME}
      - ${HOME}/.cache/nix:/home/dockeruser/.cache/nix
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /var/run/docker.sock:/var/run/docker.sock
      - ../.cache/pypoetry_docker:/home/dockeruser/.cache/pypoetry
      - ../.cache/pip_docker:/home/dockeruser/.cache/pip

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
