services:
  racecar:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        BASE_IMAGE: sebagarc/racecar2
        # BASE_IMAGE: nvidia/cuda:12.8.1-devel-ubuntu24.04
        DOCKER_UID: 1000
        DOCKER_GID: 1000
    image: local/racecar-sim
    privileged: true
    # user: "1000:1000"
    entrypoint: /home/dockeruser/racecar_ws/src/libracecar/docker/entrypoint_sim_alan.sh
    environment:
      - DISPLAY=${DISPLAY}
      # have /etc/profile.d/xdg_dirs_desktop_session.sh initialize XDG_DATA_DIRS
      - DESKTOP_SESSION=NONEMPTY
      # otherwise qt cant find icons by default so rqt_graph doesnt work
      - XDG_CURRENT_DESKTOP=GNOME
      - LOCALE_ARCHIVE=${LOCALE_ARCHIVE}
      - SSH_AUTH_SOCK=$SSH_AUTH_SOCK
      - FORCE_COLOR=1
      - BETTER_EXCEPTIONS=1
    volumes:
      - ../../racecar_ws_src:/home/dockeruser/racecar_ws/src
      - ../../:/home/dockeruser/repos
      - /nix:/nix
      - ${HOME}/.emacs.d:/home/dockeruser/.emacs.d
      # - ${HOME}/.ssh:/home/dockeruser/.ssh
      - ${HOME}:${HOME}
      - ${HOME}/.cache/nix:/home/dockeruser/.cache/nix
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /var/run/docker.sock:/var/run/docker.sock
      - ../.cache/pypoetry_docker:/home/dockeruser/.cache/pypoetry
      - ../.cache/pip_docker:/home/dockeruser/.cache/pip
      - $SSH_AUTH_SOCK:$SSH_AUTH_SOCK

      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      # - ${HOME}/.nix-profile:/home/dockeruser/.nix-profile:ro
      - ${HOME}/.local/share/fonts:/home/dockeruser/.local/share/fonts:ro
      - ${HOME}/.fontconfig:/home/dockeruser/.fontconfig:ro
      - ${HOME}/.config/fontconfig:/home/dockeruser/.config/fontconfig:ro

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
